// Men's actions
export const MEN_REQUEST_PENDING = "MEN_REQUEST_PENDING";
export const MEN_REQUEST_FAILURE = "MEN_REQUEST_FAILURE";
export const MEN_REQUEST_SUCCESS = "MEN_REQUEST_SUCCESS";

// Women's actions
export const WOMEN_REQUEST_PENDING = "WOMEN_REQUEST_PENDING";
export const WOMEN_REQUEST_FAILURE = "WOMEN_REQUEST_FAILURE";
export const WOMEN_REQUEST_SUCCESS = "WOMEN_REQUEST_SUCCESS";