// Wishlist item actions
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const LOAD_WISHLIST = "LOAD_WISHLIST";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";

// Wishlist request states
export const WISHLIST_REQUEST_PENDING = "WISHLIST_REQUEST_PENDING";
export const WISHLIST_REQUEST_SUCCESS = "WISHLIST_REQUEST_SUCCESS";
export const WISHLIST_REQUEST_FAILURE = "WISHLIST_REQUEST_FAILURE";